const museums=[
{id:'innovation',name:'明日科创营',theme:'科创教育',floor:'B1',time:45,color:'#7b61c9',image:'b1-innovation.jpg',intro:'以“科艺融合、点亮好奇”为核心，融合创客、实验、研学和表演，提供从启发到实践创新的完整教育体验。',highlights:['创客空间','数字创作中心','奇点剧场']},
{id:'energy',name:'源动未来',theme:'能源',floor:'1F',time:30,color:'#e6a33a',image:'l1-energy.jpg',intro:'从能源纵览、能源探知到节能减排，了解能源如何推动文明发展，并一起思考低碳可持续的未来。',highlights:['新生力量','节能减排','能源众语']},
{id:'mini',name:'一米世界',theme:'儿童科学',floor:'1F',time:30,color:'#55a88f',image:'l1-mini-world.jpg',intro:'在开心河岸、热闹广场和脚下都市里发现城市科学，用“科幻+童话”激发儿童的好奇心、想象力和创造力。',highlights:['超能工场','脚下都市','惊喜自然']},
{id:'material',name:'材料魔方',theme:'材料',floor:'1F',time:25,color:'#4c91b8',image:'l1-material.jpg',intro:'认识材料的特性，理解材料与人类文明、科技发展的共生关系，并展望未来材料的应用可能。',highlights:['材料超酷','材料与我','未来材料']},
{id:'rainforest',name:'雨林秘境',theme:'生态',floor:'1F',time:35,color:'#2d9ba1',image:'l1-rainforest.jpg',intro:'沉浸式体验热带雨林生态环境，以科考视角了解科学发现过程和跨学科研究，思考人与雨林的关系。',highlights:['雨林纵览','魅力雨林','雨林故事']},
{id:'wisdom',name:'智慧之光',theme:'基础科学',floor:'1F',time:35,color:'#ee7d45',image:'l1-wisdom.jpg',intro:'沿着观察现象、整理分析到理解规律的路径，通过可观、可触、可感的互动展品认识物理、数学和化学。',highlights:['互动展品','科学方法','声光电体验']},
{id:'ai',name:'明日行者',theme:'人工智能',floor:'2F',time:30,color:'#d66a76',image:'l2-ai.jpg',intro:'以人工智能发展为叙事主线，认识机器人和智能技术的应用场景，思考数字化、智能化的未来。',highlights:['回忆路','智造场','无限城 · 未来港']},
{id:'planet',name:'共生星球',theme:'地球生态',floor:'2F',time:30,color:'#4c91b8',image:'l2-planet.jpg',intro:'从地球环境和生物多样性出发，理解生态系统的运作规律，以及科技与未来视角下的共同家园。',highlights:['地球实验室','变化的地球','守护地球家园']},
{id:'exploration',name:'探索之光',theme:'探索科学',floor:'3F',time:35,color:'#6c6cc4',image:'l3-exploration.jpg',intro:'从经典科学故事走进量子科技、基因调控和相对论，回溯科学历程，想象未来科技。',highlights:['探索物质结构','探索基因之路','相对论剧场']},
{id:'flight',name:'飞行探秘',theme:'航空',floor:'3F',time:35,color:'#b97854',image:'l3-flight.jpg',intro:'体验人类把飞行梦想变成现实的百年历程，认识飞行法则、飞机制造和大国航空工程。',highlights:['飞行法则区','飞机工场','风洞体验场']},
{id:'me',name:'神奇的我',theme:'健康',floor:'3F',time:30,color:'#d66a76',image:'l3-me.jpg',intro:'从人体优势、健康新视角和脑内乾坤重新认识身体，思考健康生活方式与人类大脑潜能。',highlights:['人体优势','新述健康','脑内乾坤']}
];
const categories=['全部','B1','1F','2F','3F'];
const detailInfo={
innovation:{sections:['声音实验室：用声音观察振动、频率与共鸣。','趣味工坊：完成材料与结构挑战。','数字创作中心：体验 AI、VR/MR 创作。'],tip:'适合青少年研学，建议先查看当天课程和剧场场次。'},
energy:{sections:['能源纵览：认识煤炭、石油、太阳能等能源形态。','新生力量：观察风能、光能与储能技术协同。','节能减排：通过互动任务设计低碳城市。'],tip:'可围绕“家里的一度电从哪里来”设计观察任务。'},
mini:{sections:['开心河岸：从水流、浮力和桥梁认识工程。','超能工场：动手组合、拆解和改造。','脚下都市：观察城市地下管网、交通与生态。'],tip:'适合学龄前和小学低年级，预留充分动手时间。'},
material:{sections:['材料超酷：比较硬度、弹性、导电性和透光性。','材料与我：追踪衣物、手机和建筑材料的来处。','未来材料：了解轻量化、可循环和智能材料。'],tip:'挑一件随身物品，现场寻找它由哪些材料组成。'},
rainforest:{sections:['雨林纵览：认识分层结构、光照和水循环。','魅力雨林：观察植物、昆虫与鸟类的适应策略。','雨林故事：从科考路线理解人与自然。'],tip:'展区光线较暗，建议放慢脚步观察。'},
wisdom:{sections:['观察现象：记录光、声、力的变化。','整理分析：比较不同条件下的结果。','理解规律：把展项体验连接到日常科学问题。'],tip:'建议每个展项先操作一次再阅读说明。'},
ai:{sections:['回忆路：回看计算、感知和机器人的发展。','智造场：观察机器视觉与协作机器人。','无限城与未来港：讨论 AI 进入城市和生活。'],tip:'可以讨论哪些工作适合交给机器。'},
planet:{sections:['同住美丽家园：认识城市与自然的依存。','地球实验室：通过数据理解环境变化。','守护地球家园：把个人选择连接到生态行动。'],tip:'适合用“我今天能少用什么”做行动清单。'},
exploration:{sections:['星光河畔：从科学史上的关键问题出发。','探索物质结构之路：认识微观与量子现象。','探索基因之路与相对论剧场：理解生命信息和时空。'],tip:'内容密度较高，建议选择 2 至 3 个主题深入体验。'},
flight:{sections:['飞行法则区：用风、压强和升力解释飞机为何能飞。','飞机工场：了解结构、材料和装配。','航空体验与风洞：把飞行原理变成可操作体验。'],tip:'体验项目可能需要排队，先看现场预约提示。'},
me:{sections:['人体优势：发现身体结构与运动能力。','新述健康：从睡眠、运动和饮食理解健康。','脑内乾坤：认识记忆、情绪和大脑可塑性。'],tip:'适合全家完成“今天的健康选择”挑战。'}
};
let state={view:'home',category:'全部',query:'',trip:[]};
const app=document.querySelector('#app');
function keqi(){return '<div class="keqi-user" aria-label="科奇"><img src="keqi-user.png" alt="科奇"></div>'}
function card(m){return `<button class="museum-card" data-id="${m.id}" style="--accent:${m.color}"><span class="museum-thumb"><img src="${m.image}" alt="${m.name}官方展陈照片"></span><span class="museum-color"></span><span><h3>${m.name}</h3><div class="museum-meta">${m.theme} · ${m.floor} · 建议 ${m.time} 分钟</div><p>${m.intro}</p></span><span class="museum-arrow">›</span></button>`}
function home(){return `<div class="hero"><div><div class="eyebrow">SHANGHAI SCIENCE & TECHNOLOGY MUSEUM</div><h1>科奇带你<br>发现科学。</h1><p>2026 焕新版全楼层导览</p></div><div class="keqi-official"><img src="keqi-official.jpg" alt="上海科技馆官方吉祥物科奇"></div></div><div class="hero-photo"><img src="l1-rainforest.jpg" alt="上海科技馆雨林秘境展区"><div class="photo-wash"></div><div class="photo-caption">1F · 雨林秘境 · 图片来源：上海科技馆官网</div></div><div class="welcome"><div class="mini-keqi"></div><div><strong>你好，我是科奇</strong><p>我来自 B21 星球，喜欢科学实验和小发明。</p></div></div><div class="section-head"><h2>按楼层出发</h2><button data-view="explore">完整导览 ›</button></div><div class="floor-grid">${categories.slice(1).map(f=>`<button class="floor-card" data-floor="${f}"><strong>${f}</strong><span>${museums.filter(m=>m.floor===f).map(m=>m.name).join(' · ')}</span></button>`).join('')}</div><div class="section-head"><h2>今日推荐</h2><button data-view="explore">更多 ›</button></div><div class="museum-list">${['rainforest','ai','flight'].map(id=>card(museums.find(m=>m.id===id))).join('')}</div>`}
function explore(){const list=museums.filter(m=>(state.category==='全部'||m.floor===state.category)&&(!state.query||(`${m.name}${m.theme}${m.floor}${m.intro}`.includes(state.query))));return `<div class="eyebrow">FLOOR GUIDE</div><div class="section-head" style="margin-top:6px"><h2>全楼层导览</h2></div><label class="search"><span>⌕</span><input id="search-input" value="${state.query}" placeholder="搜索展区或关键词" aria-label="搜索展区或关键词"></label><div class="chips">${categories.map(c=>`<button class="chip ${state.category===c?'is-active':''}" data-category="${c}">${c}</button>`).join('')}</div><div class="section-head"><h2>${list.length} 个空间</h2><span style="font-size:11px;color:var(--muted)">官网 2026 数据</span></div><div class="museum-list">${list.length?list.map(card).join(''):'<div class="empty">没有找到相关展区<br>换个关键词试试吧</div>'}</div>`}
function trip(){const selected=museums.filter(m=>state.trip.includes(m.id));const total=selected.reduce((n,m)=>n+m.time,0);return `<div class="eyebrow">MY ROUTE</div><div class="section-head" style="margin-top:6px"><h2>我的行程</h2>${selected.length?'<button id="clear-trip">清空</button>':''}</div><div class="trip-summary"><strong>${total}</strong><span>分钟</span><p>${selected.length?`已收藏 ${selected.length} 个展馆，按你的节奏慢慢逛。`:'还没有收藏展馆，去展馆页挑几个吧。'}</p></div><div class="museum-list">${selected.length?selected.map(card).join(''):'<div class="empty">☆<br>把感兴趣的展馆加入这里</div>'}</div>`}
function render(){app.innerHTML=state.view==='home'?home():state.view==='explore'?explore():trip();document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>{state.view=b.dataset.view;render()});document.querySelectorAll('[data-id]').forEach(b=>b.onclick=()=>openDrawer(b.dataset.id));document.querySelectorAll('[data-category]').forEach(b=>b.onclick=()=>{state.category=b.dataset.category;render()});document.querySelectorAll('[data-floor]').forEach(b=>b.onclick=()=>{state.category=b.dataset.floor;state.view='explore';render()});const input=document.querySelector('#search-input');if(input){input.oninput=e=>{state.query=e.target.value;render();const next=document.querySelector('#search-input');next?.focus();next?.setSelectionRange(state.query.length,state.query.length)}}document.querySelector('#clear-trip')?.addEventListener('click',()=>{state.trip=[];render()});document.querySelectorAll('.tab').forEach(t=>t.classList.toggle('is-active',t.dataset.view===state.view));const badge=document.querySelector('#trip-badge');badge.hidden=!state.trip.length;badge.textContent=state.trip.length}
function openDrawer(id){const m=museums.find(x=>x.id===id);const saved=state.trip.includes(id);const detail=detailInfo[id];document.querySelector('#drawer-root').innerHTML=`<div class="drawer-backdrop" id="backdrop"><section class="drawer" role="dialog" aria-modal="true" aria-label="${m.name}详情"><div class="drawer-handle"></div><img class="drawer-cover" src="${m.image}" alt="${m.name}官方展陈照片"><div class="drawer-top"><div><div class="eyebrow">${m.theme} · ${m.floor}</div><h2>${m.name}</h2><div class="drawer-label">建议参观 ${m.time} 分钟</div></div><button class="close-btn" id="close-drawer" aria-label="关闭">×</button></div><p class="drawer-intro">${m.intro}</p><div class="detail-block"><h3>科奇带你看</h3>${detail.sections.map((x,i)=>`<div class="detail-row"><b>0${i+1}</b><p>${x}</p></div>`).join('')}</div><div class="keqi-tip"><img src="keqi-user.png" alt="科奇"><p><strong>科奇提示</strong>${detail.tip}</p></div><button class="primary-btn ${saved?'saved':''}" id="save-btn">${saved?'✓ 已在我的行程':'☆ 加入我的行程'}</button></section></div>`;document.querySelector('#close-drawer').onclick=closeDrawer;document.querySelector('#backdrop').onclick=e=>{if(e.target.id==='backdrop')closeDrawer()};document.querySelector('#save-btn').onclick=()=>{state.trip=saved?state.trip.filter(x=>x!==id):[...state.trip,id];closeDrawer();render()}}
function closeDrawer(){document.querySelector('#drawer-root').innerHTML=''}
render();
